#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 29 14:54:06 2019

@author: jon
"""

from os import listdir
import pandas as pd

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import json

import MalardInterface.DataSetQuery as d


from math import floor
from matplotlib.collections import PatchCollection
from datetime import datetime

environmentName = 'DEVv2'
#Sets the URL of the Malard ServiceGateway.
query = d.DataSetQuery('http://localhost:9000',environmentName)

stats_dir = '/home/jon/data/stats/50days/'

stats = [ pd.read_csv("{}/{}".format(stats_dir,f)) for f in listdir(stats_dir) ]

stats_df = pd.concat(stats, ignore_index=True)

stats_df = stats_df[stats_df['gridded_count'] != 0]

stats_df['density'] = stats_df['gridded_count'] / (201*201)

print(stats_df['density'].describe())

stats_df['density'].hist()


